### PR TITLE
2015 Site Updates

### PR DESCRIPTION
**Pull request by sambao21**
* Added archive page and archived 2014

## Home page
* Date Change
* Registration coming soon and remove eventbrite button
* Change schedule to Call for Paper and link to 2014 sessions
* Remove sessions
* Remove venue discount link
* Remove sponsors (except for Cerner) and link to 2015 prospectus page (which has link to pdf)

## Sessions page
* Removed sessions and link to 2014 sessions

## Sponsorship page
* Add link to pdf
* Updated table to match pdf

### CODE REVIEW

**Comment by sambao21** [comment]
Couple of comments.

* I assumed Cerner is a sponsor, so I kept that there. Can be removed if that's a wrong assumption.
* I archived 2014 exactly as is, with links to marriott and eventbrite. We can remove those, but I clicked through and they're valid urls and so it seemed legit as a snapshot in time.
* I deleted images for the sponsors and the speakers from 2015 to save space.
* Do we still need prospectus page? Since we have prospectus pdf? From home page I linked to the page, but it seemed the page is redundant and we could get rid of it and just link to the pdf file.

**Comment by kpshek** [comment]
Thanks, Sam!

>I assumed Cerner is a sponsor, so I kept that there. Can be removed if that's a wrong assumption.

Yes, Cerner is the diamond sponsor again this year.

>I archived 2014 exactly as is, with links to marriott and eventbrite. We can remove those, but I clicked through and they're valid urls and so it seemed legit as a snapshot in time.

I went ahead and removed those URLs since they aren't relevant anymore (see 62f3318c295e932a942465624789726e77bf1939)

>I deleted images for the sponsors and the speakers from 2015 to save space.

I agree with this change -- not for saving space but rather than these were only applicable to 2014

>Do we still need prospectus page? Since we have prospectus pdf? From home page I linked to the page, but it seemed the page is redundant and we could get rid of it and just link to the pdf file.

Yes. The prospectus webpage represents the current state of sponsorship availability whereas the PDF is more a description of the sponsorship options.

> I think that the current site should be tagged 2014 even though we have archive.

Can you clarify this comment? I'm not following.

**Comment by sambao21** [comment]
I just mean got tag the revision of 2014 in addition to the archive resource.

**Comment by kpshek** [comment]
Ah, good call.
https://github.com/midwestio/midwestio.github.io/tree/2014

**Pull request merged**
